config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root to: "boards#index"

  resources :boards do
    member do
      post :subscribe
    end
    resources :posts
  end
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :logo, BoardLogoUploader

  validates :title, presence: true
  validates :description, presence: true

  has_many :user_relations
  has_many :users, through: :user_relations

  has_many :owners, -> { where(user_relations: {role: 'owner'}) }, through: :user_relations,
   class_name: "User", source: :user

  has_many :subscribers, -> { where(user_relations: {role: 'user'}) }, through: :user_relations,
    class_name: "User", source: :user

  has_many :posts

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true, length: { minimum: 2, maximum: 10 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :comments

  mount_uploader :image, BoardLogoUploader

  after_create :send_notifications
  after_update :send_update_notifications

  def send_notifications
    board.subscribers.each do |user|
      NotificationMailer.new_post_notification(user, self).deliver_later
    end
    SlackNotifierJob.perform_later(self)
    ActionCable.server.broadcast("notification_for_#{self.board_id}", self.to_json)
  end


  def send_update_notifications
    #Send update update notifications
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_relations
  has_many :boards, through: :user_relations

  has_many :owned_boards, -> { where(user_relations: {role: 'owner'}) }, through: :user_relations,
   class_name: "Board", source: :board

   has_many :subscribed_boards, -> { where(user_relations: {role: 'user'}) }, through: :user_relations,
    class_name: "Board", source: :board
  has_many :comments

end

app/models/user_relation.rb
class UserRelation < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates :user_id, uniqueness: {scope: :board_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
   flash[:error] = "Yetkiniz yok."
   redirect_to(request.referrer || root_path)
  end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_board, only: [:show, :edit, :update, :subscribe]
  #before_action :authorize, only: [:edit, :update, :destroy]

  def subscribe
    @board.subscribers << current_user
    redirect_to board_path(@board), notice: "Boarda abone oldunuz."
  end

  def show
    @comment = Comment.new
  end

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def edit
    authorize @board

  end

  def update
    authorize @board
    if @board.update(board_params)
      redirect_to board_path(@board), notice: "Başarıyla güncellendi"
    else
      render :edit
    end
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      @board.owners << current_user
      redirect_to board_path(@board), notice: "Başarıyla oluşturuldu"
    else
      render :new
    end
  end

  # def authorize
  #   redirect_to(root_path, notice: "Bu islem icin yetkiniz yok") unless @board.owners.include?(current_user)
  # end

  def board_params
    params.require(:board).permit(:title, :description, :public, :slack_url, :logo, :remove_logo)
  end

  def set_board
    @board = Board.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.create(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @board = Board.find(params[:board_id])
    @post = Post.new
  end

  def create
    @board = Board.find(params[:board_id])
    @post = @board.posts.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to board_path(@board), notice: "Duyuru olusturuldu"
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to board_path(@post.board_id), notice: "Duyuru guncellendi"
    else
      render :edit
    end
  end

  def destroy
  end

  def post_params
    params.require(:post).permit(:title, :content, :image, :remove_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_form.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <%= simple_form_for @board do |f| %>
      <% if @board.errors.any? %>
        <ul>
          <% @board.errors.full_messages.each do |msg| %>
            <li>
              <%=msg%>
            </li>
          <% end %>
        </ul>
      <% end %>

      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :public %>
      <%= f.input :slack_url %>
      <%= f.input :logo %>
      <%= f.input :remove_logo, as: :boolean if @board.logo.present?  %>

      <%= f.submit "Gonder", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/edit.html.erb
Edit Board

<%= render "form" %>

app/views/boards/index.html.erb
<h1>Boards#index</h1>

<ul>
  <% @boards.each do |board| %>
    <li>
      <%= link_to board.title, board_path(board.id)%>
    </li>
  <% end %>
</ul>

app/views/boards/new.html.erb
Yeni Board Olustur

<%= render "form" %>

app/views/boards/show.html.erb
<script>
window.board_id = <%= @board.id %>
</script>
<%= javascript_include_tag 'channels/notification' %>

<div class="row">
  <div class="col-md-8">

    <h1><%= @board.title %></h1>

    <%= image_tag @board.logo.url(:thumb_fill), height: 50, width: 50 %>

    <%= render @board.posts %>

    <% if policy(@board).update? %>
      <%= link_to "Duzenle", edit_board_path(@board.id) %>
    <% end %>
  </div>

  <div class="col-md-4">

    <% unless @board.users.include?(current_user) %>
      <%= link_to "Abone Ol", subscribe_board_path(@board), method: :post, class: "btn btn-success" %>
    <% end %>
    <br />

    <% if @board.owners.include?(current_user) %>
      <%= link_to "Yeni Duyuru Gonder",  new_board_post_path(@board), class: "btn btn-success" %>
    <% end %>
    <br />

    <h3>Owners: </h3>

    <% @board.owners.each do |user| %>
      <%= user.email %> <br />
    <% end %>
 <br /> <br /> <br />

    <h3>Subscribers: </h3>

    <% @board.subscribers.each do |user| %>
      <%= user.email %> <br />
    <% end %>
  </div>
</div>

app/views/comments/_comment.html.haml
%li{id: dom_id(comment)}
  = comment.content
  = link_to "Sil", comment_path(comment), method: :delete, remote: true

app/views/comments/_comment_list.html.haml
%h3 Yorumlar
%ul{id: "comment_list_#{post.id}"}
  - post.comments.each do |comment|
    = render comment

app/views/comments/_form.html.haml
= simple_form_for @comment, remote: true do |f|
  .row
    .col-md-8
      = f.input :content, as: :string, label: false, input_html: {class: "comment_content_input"}
    .col-md-4
      = f.submit "Gonder", class: "btn btn-primary"

  = f.input :post_id, as: :hidden, input_html: {value: post.id}

app/views/comments/create.js.erb
<% if @comment.valid? %>
  var comment_html = "<%= j(render(@comment)) %>"
  $("#comment_list_<%= @comment.post_id %>").append(comment_html)
  $(".comment_content_input").val("")
<% else %>
  alert("Yorum Kaydedilemedi. <%= @comment.errors.full_messages.join(", ") %>")
<% end %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").remove()

app/views/layouts/_footer.html.erb
<footer>
  Notiboard 2017
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Notiboard", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>

        <% if current_user.present? %>
          <li><%= link_to current_user.username, "#" %></li>
          <li><%= link_to "Board Olustur", new_board_path %></li>
          <li><%= link_to "Çıkış Yap", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Giris Yap", new_user_session_path %></li>
          <li><%= link_to "Kayit Ol", new_user_registration_path %></li>

        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notiboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:error] %>
        <div class="alert alert-danger"><%= flash[:error] %></div>
      <% end %>


      <%= yield %>
    </div><!-- /.container -->

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <%= simple_form_for [@board, @post] do |f| %>
      <% if @post.errors.any? %>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li>
              <%=msg%>
            </li>
          <% end %>
        </ul>
      <% end %>

      <%= f.input :title %>
      <%= f.input :content %>
      <%= f.input :image %>
      <%= f.input :remove_image, as: :boolean if @post.image.present?  %>
      <%= f.submit "Gonder", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.haml
.panel.panel-primary
  .panel-heading= post.title
  .panel-body
    = post.content

    = render 'comments/comment_list', post: post
    = render 'comments/form', post: post

  .panel-footer
    %strong= post.created_at.to_formatted_s(:short)
    = link_to  "Duzenle", edit_board_post_path(@board.id, post)

app/views/posts/edit.html.erb
<h1>
  Duyuruyu Duzenle
</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>
  Yeni Duyuru Olustur 
</h1>

<%= render "form" %>